spring:
  datasource:
    url: jdbc:mysql://47.99.115.104:3306/offer?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: 5201314jin
    driver-class-name: com.mysql.jdbc.Driver
